# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "hw2" do |hw2|
    hw2.vm.box="bento/ubuntu-20.04"
    hw2.vm.hostname = "web.hw2.local"
    hw2.vm.network "private_network", ip: "192.168.12.5"
    hw2.vm.network "forwarded_port", guest: 80, host: 80, auto_correct: true
    hw2.vm.synced_folder "vagrant/docker/", "/vagrant"
    hw2.vm.provision "shell", path: "hw2.sh"
    hw2.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
  end

end
 
